version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_229a269e4c2c145
      SPRING_DATASOURCE_USERNAME: b58456b8d755e1
      SPRING_DATASOURCE_PASSWORD: 3547a3b0

    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3306:3306

